#!/usr/bin/env python3
"""
Aily Connector — Query API endpoints.

Auto-generated by site-skill-builder. Read-only endpoints only.

Usage:
    python3 query.py --endpoint <name> [OPTIONS]
    python3 query.py --list
"""

import argparse
import json
import os
import subprocess
import sys
import platform
import time
import urllib.request
import urllib.error

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import load_env

# cookie-provider paths
_VENV_BIN = "Scripts" if platform.system() == "Windows" else "bin"
_VENV_PY = "python.exe" if platform.system() == "Windows" else "python3"


def _cookie_provider_candidates():
    if os.environ.get("COOKIE_PROVIDER_DIR"):
        yield os.path.expanduser(os.environ["COOKIE_PROVIDER_DIR"])
    yield os.path.expanduser("~/.anyweb/deps/cookie-provider")
    yield os.path.expanduser("~/.claude/skills/cookie-provider")
    yield os.path.expanduser("~/.codex/skills/cookie-provider")


def _resolve_cookie_provider():
    for root in _cookie_provider_candidates():
        get_cookie = os.path.join(root, "scripts", "get_cookie.py")
        if not os.path.isfile(get_cookie):
            continue
        venv_python = os.path.join(root, "scripts", "venv", _VENV_BIN, _VENV_PY)
        return (venv_python if os.path.isfile(venv_python) else sys.executable), get_cookie
    return None, None


PROVIDER_PYTHON, GET_COOKIE_SCRIPT = _resolve_cookie_provider()
CREDENTIALS_FILE = os.path.expanduser("~/.aily_connector/credentials.env")

BASE_URL = "https://aily.feishu.cn"
SITE_ALIAS = "aily"

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/146.0.0.0 Safari/537.36"
)

# ── Endpoint whitelist (read-only only) ──────────────────
# Auto-generated from confirmed endpoints. DO NOT add write endpoints.
ENDPOINTS = {
    "default": {
        "method": "GET",
        "path": "/",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "app-settings": {
        "method": "GET",
        "path": "/ai/api/v1/bff/app/settings",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "admin-tenant_info": {
        "method": "GET",
        "path": "/play/api/v1/admin/tenant_info",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "v1-check_fg_access": {
        "method": "GET",
        "path": "/play/api/v1/check_fg_access",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "enterprise-knowledge": {
        "method": "GET",
        "path": "/play/api/v1/check/enterprise/knowledge",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "tcc-config": {
        "method": "GET",
        "path": "/play/api/v1/tcc/config",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "tenant_display-full_conf": {
        "method": "GET",
        "path": "/play/api/v1/user/tenant_display/full_conf",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "tenant-aily_releated_tenants": {
        "method": "GET",
        "path": "/ai/api/v1/tenant/aily_releated_tenants",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "v1-placeholder": {
        "method": "GET",
        "path": "/play/api/v1/placeholder",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "trigger-list": {
        "method": "GET",
        "path": "/play/api/v1/trigger/list",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "user-info": {
        "method": "GET",
        "path": "/play/api/v1/user/info",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "claim-status": {
        "method": "GET",
        "path": "/play/api/v1/bots/claim/status",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "ws-token": {
        "method": "GET",
        "path": "/play/api/v1/ws/token",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "entitlement-user_entitlement": {
        "method": "GET",
        "path": "/play/api/v1/entitlement/user_entitlement",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "v1-speech_access_token": {
        "method": "GET",
        "path": "/play/api/v1/speech_access_token",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "templates-types": {
        "method": "GET",
        "path": "/play/api/v1/templates/types",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "v1-runtime_templates": {
        "method": "GET",
        "path": "/play/api/v1/runtime_templates",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
    "v1-conversations": {
        "method": "GET",
        "path": "/play/api/v1/conversations",
        "description": "自动纳入: 安全只读方法 (GET)",
    },
}


def log(msg):
    print(f"[aily_connector] {msg}", file=sys.stderr)


def build_headers(csrf, cookie_string):
    headers = {
        "Cookie": cookie_string,
        "Content-Type": "application/json",
        "Accept": "application/json, text/plain, */*",
        "Origin": BASE_URL,
        "Referer": BASE_URL + "/",
        "User-Agent": USER_AGENT,
    }
    if csrf:
        headers["X-LGW-CSRF-Token"] = csrf
    return headers


def refresh_cookie_via_provider():
    """Auto-refresh cookie via cookie-provider. Returns (csrf, cookie_string) or None."""
    if not PROVIDER_PYTHON or not GET_COOKIE_SCRIPT:
        return None

    log("Refreshing cookie via cookie-provider...")
    try:
        result = subprocess.run(
            [PROVIDER_PYTHON, GET_COOKIE_SCRIPT, "--site", SITE_ALIAS, "--format", "json", "--auto-login"],
            capture_output=True, text=True, encoding="utf-8", timeout=360
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            cookies = data.get("cookies", {})
            csrf = (
                cookies.get("lgw_csrf_token", "")
                or cookies.get("csrfToken", "")
                or data.get("csrf_token", "")
            )
            cookie_string = data.get("cookie_string", "")
            if cookie_string:
                csrf = csrf or ""
                _save_refreshed_cookie(csrf, cookie_string)
                os.environ["AILY_CONNECTOR_CSRF"] = csrf
                os.environ["AILY_CONNECTOR_COOKIE"] = cookie_string
                log("[OK] cookie-provider refresh succeeded")
                return csrf, cookie_string
        elif result.returncode == 1:
            log("SSO expired, run: /cookie-provider login")
        else:
            log(f"cookie-provider failed (exit={result.returncode}): {result.stderr[:200]}")
    except subprocess.TimeoutExpired:
        log("cookie-provider timed out")
    except Exception as e:
        log(f"cookie-provider error: {e}")
    return None


def _save_refreshed_cookie(csrf, cookie_string):
    """Write refreshed cookie to credentials.env, preserving other config."""
    existing = {}
    if os.path.isfile(CREDENTIALS_FILE):
        with open(CREDENTIALS_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                key = key.strip()
                if key not in ('AILY_CONNECTOR_CSRF', 'AILY_CONNECTOR_COOKIE'):
                    existing[key] = value.strip()

    from datetime import datetime
    lines = [
        "# Aily Connector credentials",
        f"# Auto-refreshed via cookie-provider: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"AILY_CONNECTOR_CSRF={csrf}",
        f"AILY_CONNECTOR_COOKIE={cookie_string}",
    ]
    if existing:
        lines.append("")
        for k, v in existing.items():
            lines.append(f"{k}={v}")
    lines.append("")

    os.makedirs(os.path.dirname(CREDENTIALS_FILE), exist_ok=True)
    with open(CREDENTIALS_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    if sys.platform != 'win32':
        os.chmod(CREDENTIALS_FILE, 0o600)


def _do_request(url, method, payload, headers):
    """Execute a single HTTP request, return JSON response."""
    if method == "GET":
        req = urllib.request.Request(url, method="GET")
    else:
        data = json.dumps(payload).encode("utf-8") if payload else None
        req = urllib.request.Request(url, data=data, method=method)
    for k, v in headers.items():
        req.add_header(k, v)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


_SESSION_EXPIRED_CODES = {140001000, 140001001}


def api_request(url, method, payload, headers, _retried=False):
    """HTTP request with auto-retry on auth error via cookie-provider."""
    try:
        resp = _do_request(url, method, payload, headers)

        # Check for session-expired error in JSON body (HTTP 200 but login required)
        if isinstance(resp, dict) and resp.get("code") in _SESSION_EXPIRED_CODES and not _retried:
            log(f"Session expired (code {resp.get('code')}), attempting auto-refresh...")
            result = refresh_cookie_via_provider()
            if result:
                csrf, cookie_string = result
                new_headers = build_headers(csrf, cookie_string)
                log("Retrying with new cookie...")
                return api_request(url, method, payload, new_headers, _retried=True)
            log("")
            log("=" * 50)
            log("Cookie expired and auto-refresh failed.")
            log("Run: /cookie-provider login")
            log("=" * 50)
            raise SystemExit(1)

        return resp
    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        log(f"HTTP {e.code} from {url}")

        if e.code in (401, 403) and not _retried:
            log("Cookie may have expired, attempting auto-refresh...")
            result = refresh_cookie_via_provider()
            if result:
                csrf, cookie_string = result
                new_headers = build_headers(csrf, cookie_string)
                log("Retrying with new cookie...")
                return api_request(url, method, payload, new_headers, _retried=True)

            log("")
            log("=" * 50)
            log("Cookie expired and auto-refresh failed.")
            log("Run: /cookie-provider login")
            log("=" * 50)
        else:
            log(f"Response body:\n{body_text[:2000]}")

        raise SystemExit(1)
    except urllib.error.URLError as e:
        log(f"Network error: {e.reason}")
        raise SystemExit(1)


def main():
    parser = argparse.ArgumentParser(description="Aily Connector — Query API")
    parser.add_argument("--endpoint", help="Endpoint name to query")
    parser.add_argument("--list", action="store_true", help="List available endpoints")
    parser.add_argument("--params", default=None,
                        help="JSON string of request parameters (for POST endpoints)")
    parser.add_argument("--output", help="Output file path (default: stdout)")
    parser.add_argument("--page", type=int, default=None, help="Page number")
    parser.add_argument("--page-size", type=int, default=None, help="Page size")
    args = parser.parse_args()

    if args.list:
        print("Available endpoints:")
        for name, info in ENDPOINTS.items():
            print(f"  {name:30s} {info['method']:6s} {info['path']}")
            if info.get('description'):
                print(f"  {'':30s} {info['description']}")
        return

    if not args.endpoint:
        parser.error("--endpoint is required (use --list to see available endpoints)")

    # ── Validate endpoint (whitelist check) ──
    if args.endpoint not in ENDPOINTS:
        log(f"ERROR: Unknown endpoint '{args.endpoint}'")
        log(f"Available: {', '.join(ENDPOINTS.keys())}")
        raise SystemExit(1)

    ep = ENDPOINTS[args.endpoint]

    # ── Resolve credentials ──
    csrf = os.environ.get("AILY_CONNECTOR_CSRF", "")
    cookie_string = os.environ.get("AILY_CONNECTOR_COOKIE", "")

    if not cookie_string:
        result = refresh_cookie_via_provider()
        if result:
            csrf, cookie_string = result
        else:
            log("ERROR: Credentials not configured.")
            log("  Option A: run /cookie-provider login")
            log("  Option B: copy credentials.env.example to ~/.aily_connector/credentials.env")
            log("            and fill AILY_CONNECTOR_COOKIE plus AILY_CONNECTOR_CSRF")
            raise SystemExit(1)

    csrf = csrf or ""
    headers = build_headers(csrf, cookie_string)

    # ── Build request ──
    url = f"{BASE_URL}{ep['path']}"

    payload = None
    if ep["method"] == "POST":
        if args.params:
            try:
                payload = json.loads(args.params)
            except json.JSONDecodeError:
                log("ERROR: --params must be valid JSON")
                raise SystemExit(1)
        elif ep.get("default_payload"):
            payload = dict(ep["default_payload"])
        else:
            payload = {}

        # Inject pagination if supported
        if args.page is not None and payload is not None:
            payload["page"] = args.page
        if args.page_size is not None and payload is not None:
            payload["pageSize"] = args.page_size

    elif ep["method"] == "GET" and args.params:
        # Append query params for GET
        import urllib.parse
        params = json.loads(args.params)
        qs = urllib.parse.urlencode(params)
        url = f"{url}?{qs}" if "?" not in url else f"{url}&{qs}"

    # ── Execute ──
    log(f"{ep['method']} {url}")
    resp = api_request(url, ep["method"], payload, headers)

    # ── Output ──
    output_json = json.dumps(resp, ensure_ascii=False, indent=2)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output_json)
        log(f"Result written to {args.output}")
    else:
        print(output_json)

    log("Done")


if __name__ == "__main__":
    main()
